steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"


- id: 'setup'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      export PROJECT=sekhrivijayrcs1
      export BUCKET_NAME="gs://sekhrivijay-rcs-dataflow-test1"
      export TEMPLATE="${BUCKET_NAME}/templates/PubSubToBigQueryBatch.json"
      export TEMP_LOCATION="${BUCKET_NAME}/temp"
      #export GOOGLE_APPLICATION_CREDENTIALS=sa.json

- id: 'mvn version'  
  name: maven:3-jdk-8
  entrypoint: mvn
  args: ['clean', 'compile']      


