substitutions:
  # Default values
  _BUCKET_M2: 'sekhrivijay-rcs-dataflow-test1'
  _BUCKET_DATAFLOW: 'gs://sekhrivijay-rcs-dataflow-test1'
  _TEMPLATE: 'gs://sekhrivijay-rcs-dataflow-test1/templates/PubSubToBigQueryBatch.json'
  _TEMP_LOCATION: 'gs://sekhrivijay-rcs-dataflow-test1/temp'
  _PROJECT: 'sekhrivijayrcs1'

steps:
###########################################################
# Step 1: Show Branch Name
###########################################################
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"


###########################################################
# Step 2: Retrieve the cached .m2 directory from GCS
###########################################################
- id: 'Copy .m2 from GCS'
  name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - 'gs://${_BUCKET_M2}/cache/.m2'
  - '/cache/.m2'
  volumes:
  - path: '/cache/.m2'
    name: 'm2_cache'



###########################################################
# Step 3: Build
###########################################################
- id: 'Build Dataflow Template'
  name: maven:3-jdk-11
  entrypoint: bash
  args:
  - './compile_batch.sh'

  volumes:
  - path: '/cache/.m2'
    name: 'm2_cache'
  env:
  - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2  
  - PROJECT=${_PROJECT}
  - BUCKET_NAME=${_BUCKET_DATAFLOW}
  - TEMP_LOCATION=${_TEMP_LOCATION}
  - TEMPLATE=${_TEMPLATE}    



###########################################################
# Step 4: Update cached .m2 directory on GCS with any
#         additional dependencies downloaded during the
#         build.
###########################################################
- id: 'Copy .m2 back to GCS'
  name: 'gcr.io/cloud-builders/gsutil'
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - '/cache/.m2'
  - 'gs://${_BUCKET_M2}/cache/.m2/'
  volumes:
  - path: '/cache/.m2'
    name: 'm2_cache'


timeout: 7200s    
